version: '3.4'

services:
  timerapi:
    image: ${DOCKER_REGISTRY-}timerapi
    container_name: timerapi
    build:
      context: .
      dockerfile: TimerApi/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "8081:80"
      - "4431:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    networks:
      - vlan

networks:
  vlan: